/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{vue,js,ts,jsx,tsx}"],
  theme: {
    extend: {
      screens: {
        xs: "360px",
        sm: "560px",
        md: "768px",
        lg: "1060px",
        xl: "1200px",
        xxl: "1440px",
        xxxl: "1600px",
        xxxxl: "2000px",
      },
      fontFamily: {
        neueRegradeBold: ['Neue-regrade-bold', 'sans-serif'],
        neueRegradeSemibold: ['Neue-regrade-semibold', 'sans-serif'],
      },
      colors: {
        ltPrimaryLight: '#C1C9FF',
        ltPrimary: '#6270EF',
        ltPrimaryDark: '#525fdb',
        ltPrimaryBG: '#6270ef29',
        dtPrimary: '#6f7af9',
        BGLight: '#ffffff',
        BGSemiLight: '#F4F4F7',
        BGSemiNormal: '#F0F0F2',
        BGSemiDark: '#37363D',
        BGDark: '#272733',
        TextLight: '#ffffff',
        TextSemiNormal: '#9A97A7',
        TextNormal: '#7b7988',
        TextSemiDark: '#3e3d45',
        TextDark: '#26262f',
        ltBorder: '#DBDBDB',
        ltBorderNormal: '#C1BFC6',
        ltRange: '#b0b0b0',
        ltBoxShadow: '#00000029',
        ltScrollbarBG: '#dfdfdf',
        ltScrollbarThumb: '#b6b6b6',
        ltBGPositive: '#E2FCDC',
        ltBGNegative: '#FDD6DB',
        ltTextPositive: '#4DAA57',
        ltTextNegative: '#FC536B',
        ltHoverPrimary: '#E9ECFF',
        ltHoverPrimaryDark: '#828BF8',
        BGNavDropdown: '#f9f9fc',
      }
    },
  },
  plugins: [],
}